name: Test and Check on Pull Request

on:  # yamllint disable-line rule:truthy
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This cancels a run if another change is pushed to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dbt:
    name: Pull Request dbt Tests
    runs-on: ubuntu-latest

    container: datacoves/ci-basic-dbt-snowflake:2

    defaults:
      run:
        # working-directory: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/transform
        working-directory: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

    env:
      DBT_PROFILES_DIR: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/automate/dbt
      # If your dbt project is at the root.
      DATACOVES__DBT_HOME: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }} 
      # # If your dbt project is inside a transform directory.
    #   DATACOVES__DBT_HOME: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/transform 

      ##### Snowflake #####
      DATACOVES__MAIN__ACCOUNT:   ${{ vars.DATACOVES__MAIN__ACCOUNT }}

      DATACOVES__MAIN__DATABASE:  ${{ vars.DATACOVES__MAIN__DATABASE }}
      DATACOVES__MAIN__SCHEMA:    ${{ vars.DATACOVES__MAIN__SCHEMA }}

      DATACOVES__MAIN__ROLE:      ${{ vars.DATACOVES__MAIN__ROLE }}
      DATACOVES__MAIN__WAREHOUSE: ${{ vars.DATACOVES__MAIN__WAREHOUSE }}

      DATACOVES__MAIN__USER:      ${{ vars.DATACOVES__MAIN__USER }}
      DATACOVES__MAIN__PASSWORD:  ${{ secrets.DATACOVES__MAIN__PASSWORD }}

      ##### Redshift #####
      # DATACOVES__MAIN__HOST: "{{ env_var('DATACOVES__MAIN__HOST') }}"
      # DATACOVES__MAIN__USER: "{{ env_var('DATACOVES__MAIN__USER') }}"
      # DATACOVES__MAIN__PASSWORD: "{{ env_var('DATACOVES__MAIN__PASSWORD') }}"
      # DATACOVES__MAIN__DATABASE: "{{ env_var('DATACOVES__MAIN__DATABASE') }}"
      # DATACOVES__MAIN__SCHEMA: "{{ env_var('DATACOVES__MAIN__SCHEMA') }}"


    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set Secure Directory
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

      - name: List of files changed
        run: "git diff origin/${{ github.event.pull_request.base.ref }} HEAD --name-status"

      - name: Install dbt packages
        run: "dbt deps"

      - name: Run dbt build
        run: "dbt build --fail-fast"

      - name: Run governance checks
        run: "pre-commit run --from-ref origin/${{ github.event.pull_request.base.ref }} --to-ref HEAD"

